name: Docker Image CI

on:
  push:
    branches:
      - main
      - stable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: anytask-org/jupiter_notebook_docker
        username: znick
        password: ${{ secrets.DOCKER_PAT }}
        registry: ghcr.io
        tag_names: true
